
import numpy as np
import cv2
import os
import pickle
import sys
import math

import matplotlib.pyplot as plt

from torchvision.io import read_image
import torch.nn as nn
import torch.nn.functional as F
import torch
from torch.utils.data import Dataset
from torchvision import transforms
from torch.utils.tensorboard import SummaryWriter

from VideoSkeleton import VideoSkeleton
from VideoReader import VideoReader
from Skeleton import Skeleton
from GenVanillaNN import * 



class Discriminator(nn.Module):
    def __init__(self, ngpu=0):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 
        super(Discriminator, self).__init__()
        self.ngpu = ngpu
        self.model = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=4, stride=2, padding=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(256, 512, kernel_size=4, stride=2, padding=1),
            nn.BatchNorm2d(512),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(512, 1, kernel_size=4, stride=1, padding=0),
            nn.Sigmoid()  # Sigmoid to output probability
        )


    def forward(self, input):
        return self.model(input)
    

class GenGAN():
    """ class that Generate a new image from videoSke from a new skeleton posture
    Fonc generator(Skeleton)->Image
    """
    def __init__(self, videoSke, loadFromFile=False):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu") 
        self.netG = GenNNSkeToImage()
        self.netD = Discriminator()
        self.real_label = 1.
        self.fake_label = 0.
        self.filename = 'data/Dance/DanceGenGAN.pth'
        tgt_transform = transforms.Compose(
                            [transforms.Resize((64, 64)),
                            #transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
                            transforms.CenterCrop(64),
                            transforms.ToTensor(),
                            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                            ])
        self.dataset = VideoSkeletonDataset(videoSke, ske_reduced=True, target_transform=tgt_transform)
        self.dataloader = torch.utils.data.DataLoader(dataset=self.dataset, batch_size=32, shuffle=True)
        if loadFromFile and os.path.isfile(self.filename):
            print("GenGAN: Load=", self.filename, "   Current Working Directory=", os.getcwd())
            #self.netG = torch.load(self.filename)
            self.netG.load_state_dict(torch.load(self.filename))


    def train(self, n_epochs=20, lr=0.0002):
        # Define loss function and optimizers
        criterion = nn.BCELoss()
        optimizerD = torch.optim.Adam(self.netD.parameters(), lr=0.0001, betas=(0.5, 0.999))
        optimizerG = torch.optim.Adam(self.netG.parameters(), lr=0.0004, betas=(0.5, 0.999))
        
        # Learning rate scheduler
        schedulerD = torch.optim.lr_scheduler.StepLR(optimizerD, step_size=10, gamma=0.5)
        schedulerG = torch.optim.lr_scheduler.StepLR(optimizerG, step_size=10, gamma=0.5)
    

        for epoch in range(n_epochs):
            for i, (ske, real_images) in enumerate(self.dataloader):
                batch_size = real_images.size(0)
                
                # Create real and fake labels
                real_labels = torch.full((batch_size,), 0.9, dtype=torch.float).to(self.netD.device)
                #real_labels = torch.full((batch_size,), self.real_label, dtype=torch.float)
                fake_labels = torch.full((batch_size,), self.fake_label, dtype=torch.float)
                
                # Move data to the same device as the model
                ske, real_images = ske.to(self.netD.device), real_images.to(self.netD.device)
                real_labels, fake_labels = real_labels.to(self.netD.device), fake_labels.to(self.netD.device)
                
                # Add noise to real and fake images
                real_images += torch.randn_like(real_images) * 0.1
                fake_images = self.netG(ske)
                fake_images += torch.randn_like(fake_images) * 0.1

                # 1. Train the Discriminator
                self.netD.zero_grad()
                
                # Train on real images
                outputs = self.netD(real_images).view(-1)
                lossD_real = criterion(outputs, real_labels)
                lossD_real.backward()
                
                # Train on fake images generated by the generator
                fake_images = self.netG(ske)
                outputs = self.netD(fake_images.detach()).view(-1)
                lossD_fake = criterion(outputs, fake_labels)
                lossD_fake.backward()
                
                # Update the Discriminator
                optimizerD.step()
                
                # 2. Train the Generator
                self.netG.zero_grad()
                
                # Forward pass through Discriminator (trying to fool it)
                outputs = self.netD(fake_images).view(-1)
                lossG = criterion(outputs, real_labels)  # Use real labels for generator loss
                lossG.backward()
                
                # Update the Generator
                optimizerG.step()
                
                # Print statistics
                if i % 50 == 0:
                    print(f"[{epoch + 1}/{n_epochs}][{i}/{len(self.dataloader)}] "
                        f"Loss_D: {lossD_real + lossD_fake:.4f} Loss_G: {lossG:.4f}")
            schedulerD.step()
            schedulerG.step()
        # Save the model after training
        os.makedirs(os.path.dirname(self.filename), exist_ok=True)
        torch.save(self.netG.state_dict(), self.filename)
        print("Training complete. Model saved.")




    def generate(self, ske):           # TP-TODO
        """ generator of image from skeleton """
        ske_t = torch.from_numpy( ske.__array__(reduced=True).flatten() )
        ske_t = ske_t.to(torch.float32)
        ske_t = ske_t.reshape(1,Skeleton.reduced_dim,1,1) # ske.reshape(1,Skeleton.full_dim,1,1)
        normalized_output = self.netG(ske_t)
        res = self.dataset.tensor2image(normalized_output[0])
        return res




if __name__ == '__main__':
    print("test")
    force = False
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        if len(sys.argv) > 2:
            force = sys.argv[2].lower() == "true"
    else:
        filename = "data/taichi1.mp4"
    print("GenGAN: Current Working Directory=", os.getcwd())
    print("GenGAN: Filename=", filename)

    targetVideoSke = VideoSkeleton(filename)

    #if False:
    if True:    # train or load
        # Train
        gen = GenGAN(targetVideoSke, False)
        gen.train(200) #5) #200) #4
    else:
        gen = GenGAN(targetVideoSke, loadFromFile=True)    # load from file        


    for i in range(targetVideoSke.skeCount()):
        image = gen.generate(targetVideoSke.ske[i])
        #image = image*255
        nouvelle_taille = (256, 256) 
        image = cv2.resize(image, nouvelle_taille)
        cv2.imshow('Image', image)
        key = cv2.waitKey(-1)

